// Functions
function LEVEL() {
console.log("#")
console.log("#")
console.log("#")
console.log("#")
console.log("######")
console.log("")
console.log("######")
console.log("#")
console.log("######")
console.log("#")
console.log("######")
console.log("")
console.log("#      #")
console.log(" #    # ")
console.log("  #  #  ")
console.log("   #    ")
console.log("")
console.log("######")
console.log("#")
console.log("######")
console.log("#")
console.log("######")
console.log("")
console.log("#")
console.log("#")
console.log("#")
console.log("#")
console.log("######")
console.log("")
}

function EEVEE() {
    console.log("######")
    console.log("#")
    console.log("######")
    console.log("#")
    console.log("######")
    console.log("")
    console.log("######")
    console.log("#")
    console.log("######")
    console.log("#")
    console.log("######")
    console.log("")
    console.log("#      #")
    console.log(" #    # ")
    console.log("  #  #  ")
    console.log("   #    ")
    console.log("")
    console.log("######")
    console.log("#")
    console.log("######")
    console.log("#")
    console.log("######")
    console.log("")
    console.log("######")
    console.log("#")
    console.log("######")
    console.log("#")
    console.log("######")
    console.log("")
}

    function DASH() {
    console.log("#############")
    console.log("#           #")
    console.log("#   |    |  #")
    console.log("#           #")
    console.log("#    \__/   #")
    console.log("#############")
}
LEVEL()
EEVEE()
DASH()
